name: mcp_bridge
description: Dart plugin for implementing Model Context Protocol (MCP) bridge. Provides tools to build MCP bridge that can expose data, functionality, and interaction patterns to LLM applications.
version: 0.1.0
homepage: https://github.com/app-appplayer/mcp_bridge
repository: https://github.com/app-appplayer/mcp_bridge
issue_tracker: https://github.com/app-appplayer/mcp_bridge/issues

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  mcp_client:
  mcp_server:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
